import { config as loadEnv } from "dotenv";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createPublicClient, createWalletClient, encodeDeployData, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
loadEnv({path:resolve(import.meta.dirname,"../../../.env"),override:false});
const network=process.argv[2];const configs={xlayer:{chainId:196,rpc:process.env.X_LAYER_RPC},base:{chainId:8453,rpc:process.env.BASE_RPC_URL},arbitrum:{chainId:42161,rpc:process.env.ARBITRUM_RPC_URL}};const selected=configs[network];if(!selected)throw new Error("Usage: node scripts/deploy-v2.mjs <xlayer|base|arbitrum>");
const rawKey=process.env.CONTRACT_DEPLOYER_PRIVATE_KEY||process.env.TEST_WALLET_PRIVATE_KEY;if(!/^0x[a-fA-F0-9]{64}$/.test(rawKey||""))throw new Error("Deployer key is missing");const account=privateKeyToAccount(rawKey);if(process.env.TEST_WALLET_ADDRESS&&account.address.toLowerCase()!==process.env.TEST_WALLET_ADDRESS.toLowerCase())throw new Error("Deployer key/address mismatch");
const chain={id:selected.chainId,name:network,nativeCurrency:{name:"Native",symbol:network==="xlayer"?"OKB":"ETH",decimals:18},rpcUrls:{default:{http:[selected.rpc]}}};const publicClient=createPublicClient({chain,transport:http(selected.rpc,{retryCount:5,retryDelay:800})});const walletClient=createWalletClient({account,chain,transport:http(selected.rpc,{retryCount:5,retryDelay:800})});
const root=resolve(import.meta.dirname,"..");const manifestPath=resolve(root,"deployments",`${selected.chainId}.json`);const manifest=JSON.parse(await readFile(manifestPath,"utf8"));async function artifact(name){return JSON.parse(await readFile(resolve(root,"artifacts",`${name}.json`),"utf8"));}
const spotArtifact=await artifact("SpotOrderAccountFactoryV2");const autoArtifact=await artifact("AutopilotVaultFactoryV2");const registryAddress=manifest.contracts.registry.address;const oracleAddress=manifest.contracts.oracleRouter.address;const [spotGas,autoGas,gasPrice,balance]=await Promise.all([publicClient.estimateGas({account,data:encodeDeployData({abi:spotArtifact.abi,bytecode:spotArtifact.bytecode,args:[registryAddress,oracleAddress]})}),publicClient.estimateGas({account,data:encodeDeployData({abi:autoArtifact.abi,bytecode:autoArtifact.bytecode,args:[registryAddress,oracleAddress]})}),publicClient.getGasPrice(),publicClient.getBalance({address:account.address})]);const multiplier=process.env.ALLOW_TIGHT_GAS==="1"?11n:13n;const required=(spotGas+autoGas)*gasPrice*multiplier/10n;console.log(`V2 preflight ${network}: balance=${balance} requiredWith${Number(multiplier)*10-100}PercentBuffer=${required}`);if(balance<required)throw new Error(`${network} deployer balance is insufficient for both V2 factories`);if(process.argv.includes("--preflight"))process.exit(0);
async function deploy(name,args){const a=await artifact(name);const hash=await walletClient.deployContract({account,abi:a.abi,bytecode:a.bytecode,args});console.log(`${name} tx ${hash}`);const receipt=await publicClient.waitForTransactionReceipt({hash,confirmations:network==="arbitrum"?20:5,timeout:300000});if(receipt.status!=="success"||!receipt.contractAddress)throw new Error(`${name} failed`);console.log(`${name} ${receipt.contractAddress}`);return {address:receipt.contractAddress,txHash:hash,blockNumber:String(receipt.blockNumber)};}
const registry=registryAddress;const oracle=oracleAddress;const spot=await deploy("SpotOrderAccountFactoryV2",[registry,oracle]);const autopilot=await deploy("AutopilotVaultFactoryV2",[registry,oracle]);
manifest.previousFactories=[...(manifest.previousFactories||[]),{version:manifest.release||"pulse-v6.0.0",spotFactory:manifest.contracts.spotFactory,autopilotFactory:manifest.contracts.autopilotFactory,replacedAt:new Date().toISOString()}];manifest.release="pulse-v6.1.0";manifest.contracts.spotFactory=spot;manifest.contracts.autopilotFactory=autopilot;manifest.v2={guardrails:["asset allowlist","oracle-valued trade and exposure caps","slippage and daily-loss bounds","cooldown and expiry","nonce and policy version","owner-only recovery"],conditionalSpot:["buy/sell trigger direction","minimum output","batch cancel"]};await writeFile(manifestPath,JSON.stringify(manifest,null,2));
