import { useEffect, useRef, useState } from "react";
import { TonConnectButton, TonConnectUIProvider, useTonWallet, useTonConnectUI } from "@tonconnect/ui-react";
import { API_BASE } from "./api";
import { ensureTelegramReportDelivery, type TelegramReportDelivery } from "./telegramReportDelivery";
import { researchServiceTitle, researchStatus, researchDate, researchIdentity, type ResearchIdentity, type ResearchContext } from "@pulse/domain";
import { TelegramResearchReport } from "./TelegramResearchReport";
import "./telegramExperience.css";

type TelegramApp=TelegramReportDelivery & {ready:()=>void;expand:()=>void;openInvoice:(url:string,callback:(status:string)=>void)=>void};
const app=()=>(window as unknown as {Telegram?:{WebApp?:TelegramApp}}).Telegram?.WebApp;
const base=`${API_BASE}/v1/telegram/ton`;
type Row=ResearchIdentity & {id:string;stars:number|null;status:string;hasReport:boolean;createdAt:number};
type Result={orderId:string;serviceId:string;status:string;context?:ResearchContext;report?:Record<string,unknown>|null};
function TonWalletPanel(){const wallet=useTonWallet();const [ui]=useTonConnectUI();const [error,setError]=useState("");return <section className="tg-mini-wallet"><span className="tg-kicker">TON CONNECT</span><h1>Your TON<br/><em>wallet session.</em></h1><p className="tg-fine">Connect through TON Connect. Your Telegram identity owns research purchases; connecting a wallet does not authorize payments or change report access.</p><TonConnectButton/>{wallet&&<section className="tg-report-handoff"><h3>Connected TON wallet</h3><code style={{overflowWrap:"anywhere"}}>{wallet.account.address}</code><p className="tg-fine">{wallet.account.chain==="-239"?"TON mainnet":"TON testnet"} · Session restored by TON Connect. No transactions are requested by this research app.</p><button className="tg-button tg-button-secondary" onClick={()=>void ui.disconnect().catch(()=>setError("Unable to disconnect the wallet session. Try again."))}>Disconnect TON session</button></section>}{error&&<p role="alert">{error}</p>}<p className="tg-fine">Disconnecting this session keeps your Telegram reports. This research app does not offer wallet-funded execution. Report access stays with your Telegram account.</p></section>;}
function TonResearchApp(){
  const [view,setView]=useState<"explore"|"reports"|"wallet">("explore");const [telegram,setTelegram]=useState<TelegramApp|null>(null);const [signed,setSigned]=useState(false);
  const [services,setServices]=useState<Array<{id:string;stars:number|null;enabled:boolean}>>([]);const [ready,setReady]=useState(false);const [tier,setTier]=useState("global-quick");const [timeframe,setTimeframe]=useState("4H");
  const [orders,setOrders]=useState<Row[]>([]);const [orderId,setOrderId]=useState("");const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const polling=useRef(false);const deliveryAllowed=useRef(false);
  useEffect(()=>{let alive=true;let script:HTMLScriptElement|undefined;const activate=()=>{const sdk=app();if(!alive||!sdk)return;sdk.ready();sdk.expand();setTelegram(sdk);setSigned(Boolean(sdk.initData));};if(app())activate();else{script=document.createElement("script");script.src="https://telegram.org/js/telegram-web-app.js";script.onload=activate;document.head.append(script);}return()=>{alive=false;};},[]);
  const request=async(path:string,body?:unknown)=>{const initData=telegram?.initData||"";if(!initData)throw new Error("Open this Mini App from the PULSE bot.");const response=await fetch(`${base}/${path}`,{method:body===undefined?"GET":"POST",headers:{"Content-Type":"application/json","PULSE-TELEGRAM-INIT-DATA":initData},...(body===undefined?{}:{body:JSON.stringify(body)}),cache:"no-store",signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Request unavailable");return data;};
  useEffect(()=>{const controller=new AbortController();void fetch(`${base}/services`,{signal:controller.signal}).then(response=>{if(!response.ok)throw Error("Catalog unavailable");return response.json();}).then(data=>{setServices(data.services||[]);setReady(Boolean(data.checkoutReady));}).catch(()=>{if(!controller.signal.aborted)setError("TON research checkout is not configured yet.");});return()=>controller.abort();},[]);
  const library=async()=>{try{const data=await request("orders");setOrders(data.orders||[]);}catch(reason){setError(reason instanceof Error?reason.message:"Library unavailable");}};
  const read=async(id:string)=>{try{const data=await request(`orders/${id}`);setResult(data);setOrderId(id);setView("reports");}catch(reason){setError(reason instanceof Error?reason.message:"Report unavailable");}};
  useEffect(()=>{if(view==="reports"&&signed)void library();},[view,signed]);
  const finished=["completed","completed_partial","failed_terminal","manual_reconciliation","refunded"].includes(result?.status||"");
  useEffect(()=>{if(!orderId||!signed||finished)return;const timer=setInterval(()=>{if(polling.current)return;polling.current=true;void request(`orders/${orderId}`).then(data=>setResult(data)).catch(reason=>setError(reason instanceof Error?reason.message:"Report recovery unavailable")).finally(()=>{polling.current=false;});},4000);return()=>clearInterval(timer);},[orderId,signed,telegram,finished]);
  const buy=async()=>{if(busy)return;setBusy(true);setError("");try{if(!deliveryAllowed.current){if(!telegram)throw new Error("Open this Mini App from the PULSE bot.");await ensureTelegramReportDelivery(telegram);deliveryAllowed.current=true;}const invoice=await request("orders",{serviceId:tier,input:{instId:"TON-USDT",timeframe,lang:"en"}});setOrderId(invoice.orderId);setResult({orderId:invoice.orderId,serviceId:tier,status:"awaiting_payment",context:{serviceId:tier,input:{instId:"TON-USDT",timeframe}}});telegram!.openInvoice(invoice.invoiceUrl,()=>{setView("reports");void read(invoice.orderId);});}catch(reason){setError(reason instanceof Error?reason.message:"Checkout unavailable");}finally{setBusy(false);}};
  const refund=async()=>{setBusy(true);try{await request(`orders/${orderId}/refund`,{});setResult(current=>current?{...current,status:"refunded"}:current);void library();}catch(reason){setError(reason instanceof Error?reason.message:"Refund unavailable");}finally{setBusy(false);}};
  const price=services.find(service=>service.id===tier);
  return <div className="tg-mini tg-ton-app"><header className="tg-mini-header"><span className="tg-brand">PULSE <b className="tg-ton-badge">TON</b></span><span className="tg-mini-account">{signed?"TELEGRAM ACCOUNT":"BROWSER PREVIEW"}</span></header><main className="tg-mini-main">{error&&<div role="alert" className="tg-mini-notice">{error} <a href="https://t.me/pulsemi_bot?start=pulse">Open PULSE chat ↗</a></div>}{!signed&&<p className="tg-fine">Preview only. Stars purchases and saved reports require signed Telegram identity from the PULSE bot.</p>}
    {view==="explore"&&<section><span className="tg-kicker">TON MARKET RESEARCH</span><h1>Keep your<br/><em>TON pulse.</em></h1><p className="tg-fine">Quick or Pro research for TON-USDT. Pay with Stars; revisit your PULSE reports on any Telegram device. A TON wallet is optional. Allow PULSE to message you when prompted so your report can arrive in chat.</p><div className="tg-mini-services">{[["global-quick","Global Quick","Focused TON market evidence"],["global-pro","Global Pro","Deeper TON scenarios and context"]].map(([id,title,copy])=><button className={`tg-mini-service ${tier===id?"pro":""}`} key={id} onClick={()=>setTier(id)}><div><h3>{title}</h3><p>{copy}</p><span className="tg-mini-price">{services.find(service=>service.id===id)?.stars?`★ ${services.find(service=>service.id===id)!.stars} per report`:"Checkout coming soon"}</span></div></button>)}</div><label className="tg-ton-field">Timeframe<select value={timeframe} onChange={event=>setTimeframe(event.target.value)}>{["1H","4H","1D","1W"].map(value=><option key={value}>{value}</option>)}</select></label><button className="tg-button" onClick={()=>void buy()} disabled={!signed||!ready||!price?.enabled||busy}>{busy?"Opening checkout…":price?.stars?`Pay ★ ${price.stars} & generate`:"Checkout unavailable"}</button><p className="tg-fine">Research only. Failed undelivered reports offer an eligible Stars refund. EVM token checks and prediction research are not offered in this TON surface.</p></section>}
    {view==="reports"&&<section><span className="tg-kicker">YOUR PULSE TON RESEARCH</span><h1>Research<br/><em>that stays.</em></h1><button className="tg-inline-button" disabled={!signed} onClick={()=>void library()}>Refresh library</button>{result&&<section className="tg-report-handoff"><span className="tg-kicker">{researchStatus(result.status)}</span>{!result.report&&<h3>{researchIdentity(result.context||{serviceId:result.serviceId}).label}</h3>}<details className="tg-report-reference"><summary>Support reference</summary><code>{result.orderId}</code></details>{result.report?<TelegramResearchReport report={result.report} context={result.context||{serviceId:result.serviceId}}/>:<p>{result.status === "awaiting_payment" ? "Payment has not been recorded for this invoice. Review Telegram checkout if you intend to purchase." : result.status === "refunded" ? "This payment was returned in Telegram Stars." : "Your recorded payment can be recovered here. Do not pay again for this order."}</p>}{["failed_terminal","manual_reconciliation"].includes(result.status)&&!result.report&&<button className="tg-button" disabled={busy} onClick={()=>void refund()}>Refund failed report</button>}</section>}{orders.map(order=><button className="tg-mini-service" key={order.id} onClick={()=>void read(order.id)}><div><h3>{order.subject||"TON-USDT"}{order.timeframe?` · ${order.timeframe}`:""}</h3><p>{order.serviceTitle||researchServiceTitle(order.serviceId)} · {researchStatus(order.status)}{order.stars!==null?` · ${order.stars} Stars`:""}</p><small>{researchDate(order.createdAt)}</small></div></button>)}{!orders.length&&!result&&<p className="tg-fine">Your TON Mini App research purchases will appear here. Your chat report library also includes these purchases.</p>}</section>}
    {view==="wallet"&&<TonWalletPanel/>}
    </main><nav className="tg-mini-nav" aria-label="TON Mini App navigation">{([['explore','Explore'],['reports','Reports'],['wallet','TON wallet']] as const).map(([key,label])=><button key={key} className={view===key?"active":""} onClick={()=>{setError("");setView(key);}}>{label}</button>)}</nav></div>;
}
export function TelegramTonMiniApp(){const configuredReturn=import.meta.env.VITE_TELEGRAM_TON_APP_RETURN_URL as string|undefined;const returnUrl=configuredReturn?.startsWith("https://t.me/")?configuredReturn:undefined;return <TonConnectUIProvider manifestUrl={new URL("/tonconnect-manifest.json",window.location.origin).href} actionsConfiguration={returnUrl?{twaReturnUrl:returnUrl as `https://${string}`} : undefined}><TonResearchApp/></TonConnectUIProvider>;}
