export const globalResearchFixture = {
  service:"analysis_premium",tier:"premium",instId:"BTC-USDT",timeframe:"4H",generatedAt:"2026-10-04T08:30:00Z",
  analysis:{headline:"BTC holds support; confirmation is still required",summary:"The latest snapshot is constructive above support. Wait for a confirmed breakout; an alternate correction remains possible.",bias:"bullish",confidence:68,
    keyLevels:{support:[61000,60000],resistance:[63000,65000]},targets:[{label:"First target",price:63000,rationale:"Prior swing high"}],invalidation:{price:60000,condition:"A 4H close below support invalidates this setup."},
    elliottWave:{degree:"minor",currentWave:"3",structure:"candidate impulse",invalidation:60000,paths:[{type:"wave_3_continuation",label:"Wave 3 continuation",target:65000,thesis:"Requires a sustained breakout.",sequence:["Hold 61000","Break 63000"]},{type:"abc_correction",label:"A-B-C correction",target:59000,thesis:"A rejected breakout could revisit lower support.",sequence:["Reject 63000","Retest support"]}]},
    agentChecklist:["Confirm candle close","Check fresh liquidity"],riskNotes:["Thin liquidity can increase slippage."],limitations:["This is a historical snapshot, not live prices."],disclaimer:"Research only; not financial advice."},
  executionPlan:{version:"1",pair:"BTC-USDT",timeframe:"4H",observedPrice:62000,recommendation:{action:"wait",label:"Wait for confirmation",reason:"The breakout has not been confirmed."},buy:{trigger:63100,orderType:"conditional",takeProfit:65000,stopLoss:60000,riskReward:1.9}},
  technical:{pivots:{pivot:61800,s1:61000,r1:63000},fibonacci:[{ratio:.618,price:61400}],elliott:{currentWave:"3",direction:"candidate impulse",invalidation:60000,explanation:"Deterministic levels use the saved candle snapshot.",waves:[{ts:Date.parse("2026-10-02T08:00:00Z"),price:60900,label:"2"}]}},
  chart:{candles:Array.from({length:24},(_,i)=>({ts:Date.parse("2026-09-30T12:00:00Z")+i*14400000,open:60500+i*65,low:60300+i*65,high:60800+i*65,close:60600+i*65,volume:200+i}))},
  defi:{requestedAsset:"BTC",network:"xlayer",status:"unmapped",explanation:"No verified asset mapping is available."},
  rawText:"RAW_PROVIDER_DUMP",usage:{totalTokens:12345},market:{ticker:{secretDebug:"UNNECESSARY_DEBUG"}},_telegramDelivery:"PRIVATE_DELIVERY_TOKEN",chartImageBase64:"RAW_IMAGE_UPLOAD",
};
export const predictionResearchFixture = {
  service:"prediction_analysis_premium",tier:"premium",generatedAt:"2026-10-04T08:30:00Z",
  analysis:{headline:"BTC milestone remains conditional",summary:"Public evidence suggests a broad probability range; the spread currently limits entry quality.",confidence:55,stance:"NO_EDGE",marketProbabilityPct:42,fairProbabilityRange:{low:38,high:47},decision:{action:"WAIT",rationale:"The spread is too wide to establish an edge."},entryConditions:["Require a tighter spread"],noTradeConditions:["Do not trade stale evidence"],evidenceDrivers:["Spot momentum supports the thesis"],counterEvidence:["Resolution timing is uncertain"],catalystsForYes:["Sustained spot breakout"],catalystsForNo:["Support failure"],invalidationConditions:["A change in resolution rules invalidates this comparison"],limitations:["Public data is incomplete"],executionRisks:["Review outcome rules and liquidity"],disclaimer:"Probabilities are estimates, not facts or financial advice."},
  predictionContext:{partial:true,missingSources:["open interest"],markets:[{market:{id:"CaseSensitiveMarket123",question:"Will BTC reach the milestone this month?",liquidityUsd:250000,volumeUsd:1000000,endDate:"2026-10-31T23:59:00Z"},outcomes:[{name:"YES",features:{midpointProbability:.42,bestBid:.40,bestAsk:.44,spreadQuality:"wide",liquidityQuality:"medium",stale:false}}]}]},
  underlyingSpot:{instId:"BTC-USDT",timeframe:"4H",chart:globalResearchFixture.chart,technical:{...globalResearchFixture.technical,elliott:{...globalResearchFixture.technical.elliott,paths:globalResearchFixture.analysis.elliottWave.paths}},explanation:"Independent underlying 4H asset structure; not a prediction probability chart."},rawText:"RAW_PROVIDER_DUMP",
};
export const riskResearchFixture = {
  service:"safety_preflight",network:"base",headline:"Material evidence gaps require caution",summary:"Market liquidity is observable, but contract and ownership checks remain incomplete.",overallScore:54,grade:"C",verdict:"CAUTION",confidence:40,
  intelligence:{evidenceCoverage:45,criticalRisks:["Unverified upgrade authority"],positiveSignals:["Observed liquidity"],unknowns:["Holder concentration unavailable"],projectAssessment:"Project website claims need verification",promotionAssessment:"No independent promotion evidence"},
  sourceCoverage:[{name:"GeckoTerminal",status:"available",detail:"Liquidity snapshot available"},{name:"Contract scan",status:"unavailable",detail:"Provider did not return verified evidence"}],
  mostLikelyLossScenario:"An authority change could prevent exit.",checklist:[{id:"internal-check-id",title:"Review contract authority",status:"warn",detail:"Ownership is not independently verified"}],recommendations:["Verify ownership before considering any transaction"],
  token:{symbol:"TEST",name:"Test evidence token",address:"0x"+"a".repeat(40),riskScore:54,grade:"C",verdict:"CAUTION",liquidityUsd:120000,marketCapUsd:3000000,holdersEstimate:null,contractAgeDays:30,isVerified:false,providerAssessment:{source:"GeckoTerminal",score:72,metadataVerified:true},flags:["Incomplete authority evidence"],components:[{key:"internal-component-key",label:"Liquidity",score:60,reason:"Observable depth"}],limitations:["Unavailable evidence does not establish safety"]},
  evidence:{hugeProviderResponse:"UNNECESSARY_DEBUG"},_telegramDelivery:"PRIVATE_DELIVERY_TOKEN",
};
